# Generated by Django 2.2 on 2020-02-21 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('name', models.CharField(max_length=100, verbose_name='コース')),
                ('desc', models.CharField(max_length=300, verbose_name='コースの情報')),
                ('learn_times', models.IntegerField(default=0, verbose_name='コースの時間')),
                ('degree', models.CharField(choices=[('cj', '初心者'), ('zj', '中級'), ('gj', '高級')], max_length=3, verbose_name='レベル')),
                ('students', models.IntegerField(default=0, verbose_name='人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='ブックマーク')),
                ('click_nums', models.IntegerField(default=0, verbose_name='クリック数')),
                ('category', models.CharField(default='バックエンド', max_length=20, verbose_name='コース種類')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='タグ')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='コース内容')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='教える')),
                ('detail', models.TextField(verbose_name='コースの詳細')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='コース写真')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='機構名称')),
            ],
            options={
                'verbose_name': 'コース名',
                'verbose_name_plural': 'コース名',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('name', models.CharField(max_length=100, verbose_name='レスーン名')),
                ('learn_times', models.IntegerField(default=0, verbose_name='学習の時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'コースのレスーン',
                'verbose_name_plural': 'コースのレスーン',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('name', models.CharField(max_length=100, verbose_name='ビデオ名')),
                ('learn_time', models.IntegerField(default=0, verbose_name='学習の時間')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='レスーン')),
            ],
            options={
                'verbose_name': 'ビデオ',
                'verbose_name_plural': 'ビデオ',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('name', models.CharField(max_length=100, verbose_name='コース名')),
                ('file', models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='ダウンロード場所')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='コース')),
            ],
            options={
                'verbose_name': 'コースのレスーン',
                'verbose_name_plural': 'コースのレスーン',
            },
        ),
    ]
