# Generated by Django 2.2 on 2020-02-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': 'コメント', 'verbose_name_plural': 'コメント'},
        ),
    ]
