# Generated by Django 2.2 on 2020-02-21 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('name', models.CharField(max_length=20, verbose_name='都市')),
                ('desc', models.CharField(max_length=200, verbose_name='紹介')),
            ],
            options={
                'verbose_name': '都市',
                'verbose_name_plural': '都市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('name', models.CharField(max_length=50, verbose_name='機構名称')),
                ('desc', models.TextField(verbose_name='説明')),
                ('tag', models.CharField(default='全国有名', max_length=10, verbose_name='機構タグ')),
                ('category', models.CharField(choices=[('pxjg', '学校'), ('gr', '個人'), ('gx', '高校')], default='pxjg', max_length=4, verbose_name='機構種別')),
                ('click_nums', models.IntegerField(default=0, verbose_name='クリック数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='ブックマーク')),
                ('address', models.CharField(default='', max_length=100, verbose_name='住所')),
                ('students', models.IntegerField(default=0, verbose_name='人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='コース数')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City')),
            ],
            options={
                'verbose_name': '機構',
                'verbose_name_plural': '機構',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('work_years', models.IntegerField(default=0, verbose_name='仕事年数')),
                ('work_company', models.CharField(max_length=50, verbose_name='会社')),
                ('work_position', models.CharField(max_length=50, verbose_name='職位')),
                ('points', models.CharField(max_length=50, verbose_name='特徴')),
                ('click_nums', models.IntegerField(default=0, verbose_name='クリック数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='ブックマーク')),
                ('age', models.IntegerField(default=18, verbose_name='年齢')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='アイコン')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='機構名称')),
            ],
            options={
                'verbose_name': '講師',
                'verbose_name_plural': '講師',
            },
        ),
    ]
