# Generated by Django 2.2 on 2020-02-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='org/%Y/%m', verbose_name='ログ'),
        ),
    ]
