# Generated by Django 2.2 on 2020-03-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_courseorg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='認証'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_glod',
            field=models.BooleanField(default=False, verbose_name='ゴールド'),
        ),
    ]
